// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

/**
 * Logging categories for the Mining system
 */
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMining, Log, All);

// Core system categories
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningZones, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningRegistry, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningMaterials, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningMemory, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningThreading, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningTaskSystem, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningAsyncOps, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningSVO, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMiningSDF, Log, All);

// Registry-specific categories
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogZoneTypeRegistry, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMaterialRegistry, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogSDFTypeRegistry, Log, All);
MININGSPICECOPILOT_API DECLARE_LOG_CATEGORY_EXTERN(LogSVOTypeRegistry, Log, All); 